// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ubkoin/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryGetNameRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (m *QueryGetNameRequest) Reset()         { *m = QueryGetNameRequest{} }
func (m *QueryGetNameRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetNameRequest) ProtoMessage()    {}
func (*QueryGetNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb82fde15a9bafd2, []int{0}
}
func (m *QueryGetNameRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetNameRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetNameRequest.Merge(m, src)
}
func (m *QueryGetNameRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetNameRequest proto.InternalMessageInfo

func (m *QueryGetNameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type QueryGetNameResponse struct {
	Record *NameRecord `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
}

func (m *QueryGetNameResponse) Reset()         { *m = QueryGetNameResponse{} }
func (m *QueryGetNameResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetNameResponse) ProtoMessage()    {}
func (*QueryGetNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb82fde15a9bafd2, []int{1}
}
func (m *QueryGetNameResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetNameResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetNameResponse.Merge(m, src)
}
func (m *QueryGetNameResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetNameResponse proto.InternalMessageInfo

func (m *QueryGetNameResponse) GetRecord() *NameRecord {
	if m != nil {
		return m.Record
	}
	return nil
}

type QueryAllNameRequest struct {
}

func (m *QueryAllNameRequest) Reset()         { *m = QueryAllNameRequest{} }
func (m *QueryAllNameRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllNameRequest) ProtoMessage()    {}
func (*QueryAllNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb82fde15a9bafd2, []int{2}
}
func (m *QueryAllNameRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllNameRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllNameRequest.Merge(m, src)
}
func (m *QueryAllNameRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllNameRequest proto.InternalMessageInfo

type QueryAllNameResponse struct {
	Record []*NameRecord `protobuf:"bytes,1,rep,name=record,proto3" json:"record,omitempty"`
}

func (m *QueryAllNameResponse) Reset()         { *m = QueryAllNameResponse{} }
func (m *QueryAllNameResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllNameResponse) ProtoMessage()    {}
func (*QueryAllNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cb82fde15a9bafd2, []int{3}
}
func (m *QueryAllNameResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllNameResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllNameResponse.Merge(m, src)
}
func (m *QueryAllNameResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllNameResponse proto.InternalMessageInfo

func (m *QueryAllNameResponse) GetRecord() []*NameRecord {
	if m != nil {
		return m.Record
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetNameRequest)(nil), "regnull.ubkoin.ubkoin.QueryGetNameRequest")
	proto.RegisterType((*QueryGetNameResponse)(nil), "regnull.ubkoin.ubkoin.QueryGetNameResponse")
	proto.RegisterType((*QueryAllNameRequest)(nil), "regnull.ubkoin.ubkoin.QueryAllNameRequest")
	proto.RegisterType((*QueryAllNameResponse)(nil), "regnull.ubkoin.ubkoin.QueryAllNameResponse")
}

func init() { proto.RegisterFile("ubkoin/query.proto", fileDescriptor_cb82fde15a9bafd2) }

var fileDescriptor_cb82fde15a9bafd2 = []byte{
	// 363 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xb1, 0x4e, 0xeb, 0x30,
	0x18, 0x85, 0xeb, 0xde, 0xde, 0x5e, 0x5d, 0xb3, 0xb9, 0x54, 0x42, 0x05, 0x22, 0x08, 0x0c, 0xa5,
	0x48, 0xb1, 0x5a, 0x26, 0xc6, 0x76, 0x61, 0x43, 0x6a, 0x47, 0x36, 0xa7, 0xfc, 0x0a, 0x11, 0x8e,
	0x9d, 0xc6, 0x0e, 0x6a, 0x85, 0x58, 0x58, 0x18, 0x58, 0x90, 0x78, 0x00, 0x5e, 0x87, 0xb1, 0x12,
	0x0b, 0x23, 0x6a, 0x79, 0x10, 0x14, 0xc7, 0xad, 0x28, 0x2a, 0x15, 0x2c, 0x89, 0xf5, 0xe7, 0x9c,
	0xff, 0x3b, 0x39, 0x32, 0x26, 0xa9, 0x7f, 0x29, 0x43, 0x41, 0x07, 0x29, 0x24, 0x23, 0x2f, 0x4e,
	0xa4, 0x96, 0xa4, 0x9a, 0x40, 0x20, 0x52, 0xce, 0xbd, 0xfc, 0x9b, 0x7d, 0xd5, 0xb6, 0x02, 0x29,
	0x03, 0x0e, 0x94, 0xc5, 0x21, 0x65, 0x42, 0x48, 0xcd, 0x74, 0x28, 0x85, 0xca, 0x4d, 0xb5, 0x46,
	0x5f, 0xaa, 0x48, 0x2a, 0xea, 0x33, 0x05, 0xf9, 0x36, 0x7a, 0xd5, 0xf4, 0x41, 0xb3, 0x26, 0x8d,
	0x59, 0x10, 0x0a, 0x23, 0xb6, 0xda, 0x8a, 0x85, 0xda, 0xfd, 0x66, 0xe8, 0x1e, 0xe0, 0x4a, 0x37,
	0xb3, 0x9d, 0x80, 0x3e, 0x65, 0x11, 0xf4, 0x60, 0x90, 0x82, 0xd2, 0x84, 0xe0, 0x92, 0x60, 0x11,
	0x6c, 0xa0, 0x1d, 0x54, 0xff, 0xdf, 0x33, 0x67, 0xb7, 0x8b, 0xd7, 0x17, 0xa5, 0x2a, 0x96, 0x42,
	0x01, 0x39, 0xc6, 0xe5, 0x04, 0xfa, 0x32, 0x39, 0x37, 0xea, 0xb5, 0xd6, 0xae, 0xb7, 0xf4, 0x4f,
	0xbc, 0xdc, 0x94, 0x09, 0x7b, 0xd6, 0xe0, 0x56, 0x2d, 0xbd, 0xcd, 0xf9, 0x27, 0xfa, 0x9c, 0x34,
	0x1f, 0x2f, 0x21, 0xfd, 0xf9, 0x15, 0xa9, 0xf5, 0x54, 0xc4, 0x7f, 0xcd, 0x4e, 0x72, 0x8f, 0x70,
	0x29, 0x13, 0x90, 0xc6, 0x37, 0xee, 0x25, 0x7d, 0xd4, 0x0e, 0x7f, 0xa4, 0xcd, 0x63, 0xba, 0x8d,
	0xdb, 0x97, 0xf7, 0xc7, 0xe2, 0x3e, 0x71, 0x29, 0x0c, 0x59, 0x14, 0x73, 0xa0, 0x0b, 0xcd, 0xd3,
	0xac, 0x4d, 0x7a, 0x9d, 0x3d, 0x6f, 0xc8, 0x1d, 0xc2, 0xff, 0x32, 0x73, 0x9b, 0xf3, 0xd5, 0x81,
	0x16, 0x2b, 0x5a, 0x1d, 0xe8, 0x4b, 0x6f, 0xee, 0x9e, 0x09, 0xb4, 0x4d, 0x36, 0x57, 0x04, 0xea,
	0x74, 0x9e, 0x27, 0x0e, 0x1a, 0x4f, 0x1c, 0xf4, 0x36, 0x71, 0xd0, 0xc3, 0xd4, 0x29, 0x8c, 0xa7,
	0x4e, 0xe1, 0x75, 0xea, 0x14, 0xce, 0xea, 0x41, 0xa8, 0x2f, 0x52, 0xdf, 0xeb, 0xcb, 0x88, 0x5a,
	0xea, 0xcc, 0x39, 0x9c, 0x1d, 0xf4, 0x28, 0x06, 0xe5, 0x97, 0xcd, 0xa5, 0x3a, 0xfa, 0x08, 0x00,
	0x00, 0xff, 0xff, 0xfc, 0x98, 0xd9, 0x12, 0xe0, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// this line is used by starport scaffolding # 2
	Name(ctx context.Context, in *QueryGetNameRequest, opts ...grpc.CallOption) (*QueryGetNameResponse, error)
	NameAll(ctx context.Context, in *QueryAllNameRequest, opts ...grpc.CallOption) (*QueryAllNameResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Name(ctx context.Context, in *QueryGetNameRequest, opts ...grpc.CallOption) (*QueryGetNameResponse, error) {
	out := new(QueryGetNameResponse)
	err := c.cc.Invoke(ctx, "/regnull.ubkoin.ubkoin.Query/Name", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) NameAll(ctx context.Context, in *QueryAllNameRequest, opts ...grpc.CallOption) (*QueryAllNameResponse, error) {
	out := new(QueryAllNameResponse)
	err := c.cc.Invoke(ctx, "/regnull.ubkoin.ubkoin.Query/NameAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// this line is used by starport scaffolding # 2
	Name(context.Context, *QueryGetNameRequest) (*QueryGetNameResponse, error)
	NameAll(context.Context, *QueryAllNameRequest) (*QueryAllNameResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Name(ctx context.Context, req *QueryGetNameRequest) (*QueryGetNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Name not implemented")
}
func (*UnimplementedQueryServer) NameAll(ctx context.Context, req *QueryAllNameRequest) (*QueryAllNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NameAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Name_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Name(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/regnull.ubkoin.ubkoin.Query/Name",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Name(ctx, req.(*QueryGetNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_NameAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).NameAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/regnull.ubkoin.ubkoin.Query/NameAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).NameAll(ctx, req.(*QueryAllNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "regnull.ubkoin.ubkoin.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Name",
			Handler:    _Query_Name_Handler,
		},
		{
			MethodName: "NameAll",
			Handler:    _Query_NameAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ubkoin/query.proto",
}

func (m *QueryGetNameRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetNameRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetNameRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetNameResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetNameResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetNameResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Record != nil {
		{
			size, err := m.Record.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllNameRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllNameRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllNameRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryAllNameResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllNameResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllNameResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Record) > 0 {
		for iNdEx := len(m.Record) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Record[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetNameRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetNameResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Record != nil {
		l = m.Record.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllNameRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryAllNameResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Record) > 0 {
		for _, e := range m.Record {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetNameRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetNameRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetNameRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetNameResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetNameResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetNameResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Record", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Record == nil {
				m.Record = &NameRecord{}
			}
			if err := m.Record.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllNameRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllNameRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllNameRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllNameResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllNameResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllNameResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Record", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Record = append(m.Record, &NameRecord{})
			if err := m.Record[len(m.Record)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
